# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typ_wydatku',
            name='typ',
            field=models.BooleanField(default=False),
        ),
    ]
