# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0002_typ_wydatku_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typ_wydatku',
            old_name='typ',
            new_name='dochod',
        ),
    ]
