# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0003_auto_20161025_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_wydatkow',
            name='dochod',
            field=models.BooleanField(default=False),
        ),
    ]
