# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0005_podtyp_wydatku_wydatek'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_wydatkow',
            name='podtyp',
            field=models.CharField(default='-', max_length=48),
            preserve_default=False,
        ),
    ]
