# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0006_baza_wydatkow_podtyp'),
    ]

    operations = [
        migrations.AddField(
            model_name='baza_wydatkow',
            name='oszczednosci',
            field=models.BooleanField(default=False),
        ),
    ]
