# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0007_baza_wydatkow_oszczednosci'),
    ]

    operations = [
        migrations.AddField(
            model_name='typ_wydatku',
            name='oszczednosci',
            field=models.BooleanField(default=False),
        ),
    ]
