# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-25 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0008_typ_wydatku_oszczednosci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baza_wydatkow',
            name='dzien',
        ),
        migrations.RemoveField(
            model_name='baza_wydatkow',
            name='okres',
        ),
    ]
