# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0009_auto_20180525_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typ_wydatku',
            name='nazwa_skrocona',
        ),
        migrations.AlterField(
            model_name='baza_wydatkow',
            name='podtyp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybudget.Podtyp_wydatku'),
        ),
        migrations.AlterField(
            model_name='baza_wydatkow',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybudget.Typ_wydatku'),
        ),
    ]
