# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-01 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybudget', '0011_auto_20180601_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podtyp_wydatku',
            name='podtyp_wydatku',
            field=models.CharField(max_length=45),
        ),
    ]
